name: 'voucher_analytics'
version: '1.0.0'
config-version: 2
profile: 'voucher_profile' 

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  # voucher_analytics:
  #   example:
      +materialized: view